# Site settings
title: Podcast Setup
email: pekalicious@gmail.com
description: A website dedicated to finding the best setup for distraction-free podcast listening
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://podcast-setup.netlify.com/" # the base hostname & protocol for your site
twitter_username: pekalicious
github_username:  pekalicious
google_analytics: UA-6605771-10

# Build settings
markdown: kramdown

# plugins:
#   - jekyll-timeago

# Make sure Jekyll loads sass the "correct" way
sass:
  load_paths:
    - _sass
    - node_modules

# Force Jekyll to load node_modules
exclude: []

collections:
  devices:
    title: Devices
    output: true
    permalink: /devices/:title
  headphones:
    title: Headphones
    output: true
    permalink: /headphones/:title
  apps:
    title: Apps
    output: true
    permalink: /apps/:title